# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VigeAffineCipherUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(773, 552)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 301, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 50, 151, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 121, 19))
        self.label_3.setObjectName("label_3")
        self.vigeCifraPush = QtWidgets.QPushButton(self.centralwidget)
        self.vigeCifraPush.setGeometry(QtCore.QRect(30, 150, 171, 27))
        self.vigeCifraPush.setObjectName("vigeCifraPush")
        self.ClaveCifrar = QtWidgets.QLineEdit(self.centralwidget)
        self.ClaveCifrar.setGeometry(QtCore.QRect(100, 110, 113, 27))
        self.ClaveCifrar.setObjectName("ClaveCifrar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 61, 20))
        self.label_4.setObjectName("label_4")
        self.vigeDecifraPush = QtWidgets.QPushButton(self.centralwidget)
        self.vigeDecifraPush.setGeometry(QtCore.QRect(500, 150, 171, 27))
        self.vigeDecifraPush.setObjectName("vigeDecifraPush")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 80, 141, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 110, 71, 20))
        self.label_6.setObjectName("label_6")
        self.ClaveDecifrar = QtWidgets.QLineEdit(self.centralwidget)
        self.ClaveDecifrar.setGeometry(QtCore.QRect(570, 110, 113, 27))
        self.ClaveDecifrar.setObjectName("ClaveDecifrar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 80, 79, 19))
        self.label_7.setObjectName("label_7")
        self.VigeLabel = QtWidgets.QLabel(self.centralwidget)
        self.VigeLabel.setGeometry(QtCore.QRect(350, 80, 141, 19))
        self.VigeLabel.setObjectName("VigeLabel")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(270, 330, 121, 19))
        self.label_9.setObjectName("label_9")
        self.AlfaText = QtWidgets.QLineEdit(self.centralwidget)
        self.AlfaText.setGeometry(QtCore.QRect(100, 360, 113, 27))
        self.AlfaText.setObjectName("AlfaText")
        self.BetaText = QtWidgets.QLineEdit(self.centralwidget)
        self.BetaText.setGeometry(QtCore.QRect(310, 360, 113, 27))
        self.BetaText.setObjectName("BetaText")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 360, 61, 19))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(250, 360, 61, 19))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(220, 440, 91, 19))
        self.label_12.setObjectName("label_12")
        self.AffineLabel = QtWidgets.QLabel(self.centralwidget)
        self.AffineLabel.setGeometry(QtCore.QRect(210, 460, 261, 19))
        self.AffineLabel.setObjectName("AffineLabel")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 410, 661, 19))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 460, 121, 19))
        self.label_15.setObjectName("label_15")
        self.AffineCifraPush = QtWidgets.QPushButton(self.centralwidget)
        self.AffineCifraPush.setGeometry(QtCore.QRect(40, 490, 171, 27))
        self.AffineCifraPush.setObjectName("AffineCifraPush")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(490, 460, 141, 19))
        self.label_16.setObjectName("label_16")
        self.AffineDecifraPush = QtWidgets.QPushButton(self.centralwidget)
        self.AffineDecifraPush.setGeometry(QtCore.QRect(480, 490, 171, 27))
        self.AffineDecifraPush.setObjectName("AffineDecifraPush")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(460, 360, 41, 19))
        self.label_13.setObjectName("label_13")
        self.anilloAffine = QtWidgets.QLineEdit(self.centralwidget)
        self.anilloAffine.setGeometry(QtCore.QRect(510, 360, 113, 27))
        self.anilloAffine.setObjectName("anilloAffine")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(320, 170, 121, 19))
        self.label_17.setObjectName("label_17")
        self.AEYAEE_ALFA = QtWidgets.QLineEdit(self.centralwidget)
        self.AEYAEE_ALFA.setGeometry(QtCore.QRect(100, 220, 113, 27))
        self.AEYAEE_ALFA.setObjectName("AEYAEE_ALFA")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(40, 220, 61, 19))
        self.label_18.setObjectName("label_18")
        self.AEYAEE_ANI = QtWidgets.QLineEdit(self.centralwidget)
        self.AEYAEE_ANI.setGeometry(QtCore.QRect(300, 220, 113, 27))
        self.AEYAEE_ANI.setObjectName("AEYAEE_ANI")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(250, 220, 41, 19))
        self.label_19.setObjectName("label_19")
        self.AEYAEE_RES = QtWidgets.QLabel(self.centralwidget)
        self.AEYAEE_RES.setGeometry(QtCore.QRect(120, 290, 621, 19))
        self.AEYAEE_RES.setObjectName("AEYAEE_RES")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 290, 91, 19))
        self.label_20.setObjectName("label_20")
        self.AEYAEE_Push = QtWidgets.QPushButton(self.centralwidget)
        self.AEYAEE_Push.setGeometry(QtCore.QRect(200, 260, 101, 27))
        self.AEYAEE_Push.setObjectName("AEYAEE_Push")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cryptografia"))
        self.label.setText(_translate("MainWindow", "Affine Cipher and Vigenere Cipher"))
        self.label_2.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.label_3.setText(_translate("MainWindow", "Cifrar Archivo"))
        self.vigeCifraPush.setText(_translate("MainWindow", "Seleccionar Archivo"))
        self.label_4.setText(_translate("MainWindow", "Clave = "))
        self.vigeDecifraPush.setText(_translate("MainWindow", "Seleccionar Archivo"))
        self.label_5.setText(_translate("MainWindow", "Decifrar Archivo"))
        self.label_6.setText(_translate("MainWindow", "Clave ="))
        self.label_7.setText(_translate("MainWindow", "Estatus:"))
        self.VigeLabel.setText(_translate("MainWindow", "Listo!"))
        self.label_9.setText(_translate("MainWindow", "Affine Cipher"))
        self.label_10.setText(_translate("MainWindow", "Alfa = "))
        self.label_11.setText(_translate("MainWindow", "Beta = "))
        self.label_12.setText(_translate("MainWindow", "Estatus :"))
        self.AffineLabel.setText(_translate("MainWindow", "Listo!"))
        self.label_14.setText(_translate("MainWindow", "Nota: Si alfa y beta estan vacios se generara un par, de forma aleatorio"))
        self.label_15.setText(_translate("MainWindow", "Cifrar Archivo"))
        self.AffineCifraPush.setText(_translate("MainWindow", "Seleccionar Archivo"))
        self.label_16.setText(_translate("MainWindow", "Decifrar Archivo"))
        self.AffineDecifraPush.setText(_translate("MainWindow", "Seleccionar Archivo"))
        self.label_13.setText(_translate("MainWindow", "N = "))
        self.label_17.setText(_translate("MainWindow", "AE Y AEE"))
        self.label_18.setText(_translate("MainWindow", "Alfa = "))
        self.label_19.setText(_translate("MainWindow", "N = "))
        self.AEYAEE_RES.setText(_translate("MainWindow", "Prueba!!"))
        self.label_20.setText(_translate("MainWindow", "Resultado:"))
        self.AEYAEE_Push.setText(_translate("MainWindow", "Probar"))
